### PR TITLE
Fixing Dependencies

### PR DESCRIPTION
**Pull request by spenceradolph**
This PR fixes problems with outdated dependencies and another small error regarding uuid/v4 import and usage.

### CODE REVIEW

**Comment by spenceradolph** [comment]
Hoping to link this to https://github.com/oktadeveloper/okta-node-express-typescript-react-example/issues/5

**Comment by mraible** [comment]
Thanks @spenceradolph! I'll get the blog post updated and this PR merged next week.

**Comment by mraible** [comment]
@spenceradolph I updated *all* the dependencies in this example and created a new PR at https://github.com/oktadeveloper/okta-node-express-typescript-react-example/pull/7. However, I can't get things to work just yet.

When I run `npm run dev`, I get an error that the `OKTA_ORG_URL` is undefined.

```
Using ts-node version 8.10.2, typescript version 3.9.3
Error: Your Okta URL must start with https. Current value: undefined/oauth2/default. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
```

I have everything defined in `.env` in the root directory.

```
OKTA_ORG_URL=https://dev-133320.okta.com
OKTA_CLIENT_ID=XXX
OKTA_TOKEN=YYY
```

**Comment by mraible** [comment]
@spenceradolph I'm closing this PR in favor of https://github.com/oktadeveloper/okta-node-express-typescript-react-example/pull/7. 

I'd like to send you an Okta t-shirt for your efforts. Can you please send me your mailing address and t-shirt size to matt.raible@okta.com? Thanks!

**Pull request closed without merging**
